# fly.toml app configuration file generated for simple-datastar-examples on 2025-07-01T19:25:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-datastar-examples'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.23.3'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
